spring:
  profiles:
    active: prod
  application:
    name: WitBoot
    version: @project.version@

logging:
  config: classpath:log4j2-spring.xml
  level:
    root: info
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
    # org.springframework: info
    # com.witboot: info